apiVersion: v1
kind: ConfigMap
metadata:
  name: asdasd-configmap
  namespace: deviceshifu
  annotations:
    workspace.id: "e9fb8640-5ebc-4133-9048-e013c7d5cf5f"
    workspace.name: "test_worksapce1"
data:
  driverProperties: |
    driverSku: HTTP USB Camera Device
    driverImage: edgenesis/usb-camera:v0.0.1
  instructions: |
    instructions:
      video:
      capture:
      probe:
  telemetries: |
    telemetries:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-asdasd
    workspace.id: "e9fb8640-5ebc-4133-9048-e013c7d5cf5f"
    workspace.name: "test_worksapce1"
  name: deviceshifu-asdasd
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-asdasd
  template:
    metadata:
      labels:
        app: deviceshifu-asdasd
        workspace.id: "e9fb8640-5ebc-4133-9048-e013c7d5cf5f"
        workspace.name: "test_worksapce1"
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:nightly
          name: deviceshifu-asdasd
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-asdasd"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
        - image: edgenesis/usb-camera:v0.0.2
          securityContext:
            privileged: true
          name: camera-python
          env:
            - name: VIDEONUMBER
              value: "0"
          volumeMounts:
            - name: video
              mountPath: "/dev"
          resources:
      volumes:
        - name: deviceshifu-config
          configMap:
            name: asdasd-configmap
        - name: video
          hostPath:
            path: /dev
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-asdasd
    workspace.id: "e9fb8640-5ebc-4133-9048-e013c7d5cf5f"
    workspace.name: "test_worksapce1"
  name: deviceshifu-asdasd
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-asdasd
  type: ClusterIP
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-asdasd
  namespace: devices
  annotations:
    workspace.id: "e9fb8640-5ebc-4133-9048-e013c7d5cf5f"
    workspace.name: "test_worksapce1"
spec:
  sku: "HTTP USB Camera Device"
  connection: Ethernet
  address: 0.0.0.0:5001
  protocol: HTTP
