apiVersion: v1
kind: ConfigMap
metadata:
  name: asd-configmap
  namespace: deviceshifu
  labels:
    app: deviceshifu-asd
    workspace_id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
    workspace_name: "123"
data:
  driverProperties: |
    driverSku: Robot Dog MQTT Device
    driverImage: robot-dog-mqtt:latest
---

apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-asd
  namespace: devices
  labels:
    app: deviceshifu-asd
    workspace_id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
    workspace_name: "123"
  annotations:
    workspace.id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
    workspace.name: "123"
    template.id: "robotdog-mqtt-v1"
spec:
  sku: "Robot Dog MQTT Device"
  connection: Ethernet
  address: "192.168.4.101:43893"
  protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-asd
    workspace_id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
  name: deviceshifu-asd
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-asd
  template:
    metadata:
      labels:
        app: deviceshifu-asd
        workspace_id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
    spec:
      containers:
        - image: edgenesis/deeprobotics-robotdog-mqtt:v0.0.1
          name: deviceshifu-asd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-asd"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: MQTT_BROKER_ADDRESS
              value: ""
            
            # No MQTT authentication configured in workspace
            
            - name: CONFIG_MOUNT_PATH
              value: "/etc/edgedevice/config"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: asd-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-asd
    workspace_id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
  name: deviceshifu-asd
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: deviceshifu-asd
  type: ClusterIP
