apiVersion: v1
kind: ConfigMap
metadata:
  name: <no value>-configmap
  namespace: deviceshifu
  annotations:
    workspace.id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
    workspace.name: "123"
data:
  driverProperties: |
    driverSku: opcua-led-light-v1
    driverImage: 
  instructions: |
    instructions:
      "number":
        protocolPropertyList:
          OPCUANodeID: "ns=1;s=number"
      "light":
        protocolPropertyList:
          OPCUANodeID: "ns=1;s=light"
  telemetries: |
    telemetries:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-<no value>
    workspace.id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
    workspace.name: "123"
  name: deviceshifu-<no value>
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-<no value>
  template:
    metadata:
      labels:
        app: deviceshifu-<no value>
        workspace.id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
        workspace.name: "123"
    spec:
      containers:
        - image: edgehub/deviceshifu-http-opcua:v0.64.0
          name: deviceshifu-<no value>
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-<no value>"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: <no value>-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-<no value>
    workspace.id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
    workspace.name: "123"
  name: deviceshifu-<no value>
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-<no value>
  type: LoadBalancer
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-<no value>
  namespace: devices
  annotations:
    workspace.id: "dec15060-dc3e-4f61-8cd8-9187b99760bc"
    workspace.name: "123"
spec:
  sku: "OPC UA LED Light"
  connection: Ethernet
  address: "<no value>"
  protocol: "OPCUA"
  protocolSettings:
    OPCUASetting:
      AuthenticationMode: Anonymous
