apiVersion: v1
kind: ConfigMap
metadata:
  name: <no value>-configmap
  namespace: deviceshifu
  labels:
    app: deviceshifu-<no value>
    workspace_id: "8f43a199-32ac-4fe2-9044-e7dbe634308e"
    workspace_name: "asdaaa"
data:
  driverProperties: |
    driverSku: Robot Dog MQTT Device
    driverImage: robot-dog-mqtt:latest
---

apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-<no value>
  namespace: devices
  labels:
    app: deviceshifu-<no value>
    workspace_id: "8f43a199-32ac-4fe2-9044-e7dbe634308e"
    workspace_name: "asdaaa"
  annotations:
    workspace.id: "8f43a199-32ac-4fe2-9044-e7dbe634308e"
    workspace.name: "asdaaa"
    template.id: "robotdog-mqtt-v1"
spec:
  sku: "Robot Dog MQTT Device"
  connection: Ethernet
  address: "<no value>"
  protocol: UDP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-<no value>
    workspace_id: "8f43a199-32ac-4fe2-9044-e7dbe634308e"
  name: deviceshifu-<no value>
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-<no value>
  template:
    metadata:
      labels:
        app: deviceshifu-<no value>
        workspace_id: "8f43a199-32ac-4fe2-9044-e7dbe634308e"
    spec:
      containers:
        - image: edgenesis/deeprobotics-robotdog-mqtt:v0.0.1
          name: deviceshifu-<no value>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: "edgedevice-<no value>"
            - name: EDGEDEVICE_NAMESPACE
              value: "devices"
            - name: MQTT_BROKER_ADDRESS
              value: ""
            
            # No MQTT authentication configured in workspace
            
            - name: CONFIG_MOUNT_PATH
              value: "/etc/edgedevice/config"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: <no value>-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-<no value>
    workspace_id: "8f43a199-32ac-4fe2-9044-e7dbe634308e"
  name: deviceshifu-<no value>
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: deviceshifu-<no value>
  type: ClusterIP
